### ISSUE TITLE
The server container stops due to not being able to install packages

### ISSUE THREAD

**Issue by mrfzd** [gfcf14/react-node-mysql-docker-boilerplate#4]
internal/modules/cjs/loader.js:638
server_1      |     throw err;
server_1      |     ^
server_1      |
server_1      | Error: Cannot find module 'cors'
server_1      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)    
server_1      |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
server_1      |     at Module.require (internal/modules/cjs/loader.js:692:17)
server_1      |     at require (internal/modules/cjs/helpers.js:25:18)
server_1      |     at Object.<anonymous> (/app/index.js:1:14)
server_1      |     at Module._compile (internal/modules/cjs/loader.js:778:30)
server_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)       
server_1      |     at Module.load (internal/modules/cjs/loader.js:653:32)
server_1      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
server_1      |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
server_1      | error Command failed with exit code 1.
server_1      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

**Comment by mrfzd** [comment]
![image](https://user-images.githubusercontent.com/7137600/80295923-f680a600-876e-11ea-8abf-6d8ff7521331.png)

**Comment by mrfzd** [comment]
I've tested the phpMyAdmin and client and they are both working, I assume the mysql should work otherwise the phpMyAdmin wouldn't

It's only the server that's keep bugging and somehow not able to install packages, to what it looks like to me at least

Any suggestions

**Comment by mrfzd** [comment]
BTW thank you for the tut and the codes, it means a lot

**Comment by gfcf14** [comment]
@FarzadOfficial I'm so sorry I didn't see this until now. From your error `Error: Cannot find module 'cors'` it seems you don't have `cors` installed. Could you please show me your `package.json` for the `server`?
